### PR TITLE
Add black box slides

### PR DESCRIPTION
**Pull request by searciniegas**
- Created `slides-resources/08-black_box.md` containing slides for topic 8: black box explainability
- Added visuals for topic 8 under `slides-resources\images`

### CODE REVIEW

**Review by danielrazavi — APPROVED** [review]

**Review by ErikinBC — CHANGES_REQUESTED** [review]
Hi Santiago,

Thanks for putting the material together, looks great overall.

I have a few follow-up requests however before this PR is merged:

- You mention Knockoffs in the Outline, but there aren’t any slides about the method
- Please add a relevant image to each section. We currently have images for the SHAP and LIME sections, but not for Black Box Models, Local Methods, Global Methods, Global Surrogates, HRT, and Knockoffs (once it’s added)
- In general, the text needs to be balanced by visuals


Would you be able to have these changes ready for EOD Wednesday/first thing Thursday (9am) so I have time to make my own modifications before the Thursday evening lecture?

**Comment by danielrazavi** [comment]
@searciniegas please add a description in your pull request, outlining exactly what you're code changes are.

**Comment by searciniegas** [comment]
> Hi Santiago,
> 
> Thanks for putting the material together, looks great overall.
> 
> I have a few follow-up requests however before this PR is merged:
> 
> * You mention Knockoffs in the Outline, but there aren’t any slides about the method
> * Please add a relevant image to each section. We currently have images for the SHAP and LIME sections, but not for Black Box Models, Local Methods, Global Methods, Global Surrogates, HRT, and Knockoffs (once it’s added)
> * In general, the text needs to be balanced by visuals
> 
> Would you be able to have these changes ready for EOD Wednesday/first thing Thursday (9am) so I have time to make my own modifications before the Thursday evening lecture?

Hi Erik, I'll address these issues this evening. Thanks!

**Comment by searciniegas** [comment]
- Added relevant visuals for each section
- Corrected the outline slide

**Review by ErikinBC — APPROVED** [review]

**Pull request merged**
